[ARO][#3] Adding Combination, SFKPermutations and tests
ProjetSI-FC/script pull request #19
Opened 2023-11-08 20:15 UTC by AntoineRoura

Add Combination class as model, SpotFileKeywordsPermutations class as controller and testing corresponding functions in CombinationTest and SpotFileKeywordsPermutationsTest classes.

2023-11-14 21:07 UTC, TheDestiny45 requested changes

2023-11-14 21:07 UTC, TheDestiny45 commented on app/src/main/java/projetsi/controllers/test
Incorrect file name with the class name.
In addition, this is a test class in should be in the following directory :
src/test/java/projetsi/controllers

2023-11-14 21:07 UTC, TheDestiny45 commented on app/src/main/java/projetsi/controllers/SpotFileKeywordsPermutations.java
> +        }
Format problem (tab) ?

2023-11-14 21:07 UTC, TheDestiny45 commented on .DS_Store
Add all the .DS_Store to the gitignore

2023-11-24 23:45 UTC, TheDestiny45 commented on app/src/main/java/projetsi/models/BlockingQueue.java
Class `BlockingQueue` already exists in `java.util.concurrent.BlockingQueue;`

2023-11-24 23:45 UTC, TheDestiny45 commented on app/src/main/java/projetsi/models/SpotFileKeywordsPermutationsProducer.java
> +                spotFileKeywordsPermutationsQueue.put(spotFileKeywordsPermutations);
```suggestion
                spotFileKeywordsPermutationsQueue.put(spotFileKeywordsPermutations);
```

2023-11-24 23:45 UTC, TheDestiny45 commented on app/src/main/java/projetsi/models/SpotFileKeywordsPermutations.java
> +public class SpotFileKeywordsPermutations implements SpotfileKeywordsPermutations {
Maybe make the class name diffrent from the interface it's implementing ?

2023-11-28 07:54 UTC, baptiste1403 requested changes
see messages

2023-11-28 07:54 UTC, baptiste1403 commented on app/src/main/java/projetsi/models/SpotFileKeywordsPermutations.java
> +    public void computePermutations() {
IS there a way to compute combination on demand because I don't think you can fit all permutation on memory

2024-01-11 21:33 UTC, TheDestiny45 approved these changes

2024-01-11 21:34 UTC, merged